### ISSUE TITLE
User Role Enum사용 건의

### ISSUE THREAD

**Issue by whdgnszz1** [jane5am/Streaming#1]
# 이슈사항: User entity의 role부분은 Enum으로 사용하는 것이 좋아보입니다.

```java
package sparta.streaming.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long userId;

    @Column(name = "user_name", nullable = false)
    private String userName;
    private String password;
    private String email;
    private String role;

    @PrePersist
    protected void onCreate() {
        this.role = "USER";
    }
}
```

# 내용
1. 타입 안전성
Enum은 고정된 상수 집합을 정의합니다. 문자열을 사용하면 실수로 잘못된 값을 할당할 수 있지만, Enum을 사용하면 컴파일 시점에 이러한 오류를 잡을 수 있습니다.
```java
public enum Role {
    USER, ADMIN, UPLOADER
}
```
이렇게 정의하면, Role.USER와 같은 형태로 사용하게 되어 잘못된 문자열 값을 사용하는 실수를 방지할 수 있습니다.

2. 가독성 및 유지보수성
Enum을 사용하면 코드의 가독성이 좋아지고, 역할에 대한 정의가 명확해져서 다른 개발자들이 코드를 이해하기 쉽습니다. 또한, 역할이 변경되거나 추가될 때 한 곳만 수정하면 되므로 유지보수가 용이합니다.
```java
@Column(name = "role", nullable = false)
@Enumerated(EnumType.STRING)
private Role role;
```

3. 유효성 검사
Enum을 사용하면 유효하지 않은 역할 값이 들어오는 것을 원천적으로 방지할 수 있습니다. 예를 들어, 문자열을 사용할 때는 "user", "admin" 등 오타나 대소문자 구분 문제로 인한 오류가 발생할 수 있습니다.
```java
user.setRole("user"); // 문자열 사용 시 오류 발생 가능
user.setRole(Role.USER); // Enum 사용 시 안전
```

4. 비즈니스 로직과의 연관성
특정 역할에 따라 다른 비즈니스 로직이 적용되는 경우 Enum을 사용하면 이러한 로직을 깔끔하게 관리할 수 있습니다. Enum에 메서드를 추가하여 역할에 따라 다른 동작을 정의할 수도 있습니다.
```java
public enum Role {
    USER, ADMIN, MODERATOR;

    public boolean canEditContent() {
        return this == ADMIN || this == MODERATOR;
    }
}
```

5. 데이터베이스 저장
@Enumerated(EnumType.STRING) 애너테이션을 사용하면 Enum 값이 데이터베이스에 문자열로 저장됩니다. 이로 인해 저장된 값이 더 이해하기 쉬워지고, 데이터베이스에서 직접 쿼리를 실행할 때도 유용합니다.
```java
@Enumerated(EnumType.STRING)
@Column(name = "role", nullable = false)
private Role role;
```

**Comment by jane5am** [comment]
지적 감사합니다! 읽어보니 고정으로 사용하는게 확실히 추후 실수 방지에 좋은 것 같습니다
코드 수정해놓았습니다!
