### ISSUE TITLE
로그 출력 시 slf4j 사용 권장

### ISSUE THREAD

**Issue by whdgnszz1** [jane5am/Streaming#3]
# 이슈사항
src/main/java/sparta/streaming/user/OAuth2UserService.java에 system.out을 사용하여 로그를 출력하는 코드가 있는데

로그를 찍을 때 system.out은 사용하지 않는 것이 좋으며, slf4j를 사용하는 것이 좋아보입니다.

# 내용
1. 로그 레벨 관리
slf4j와 같은 로깅 프레임워크는 로그 메시지를 다양한 레벨 (예: DEBUG, INFO, WARN, ERROR)로 구분하여 관리할 수 있습니다. 이를 통해 애플리케이션의 실행 상태와 문제를 더 효과적으로 모니터링할 수 있습니다.

```java
log.debug("Debugging message");
log.info("Informational message");
log.warn("Warning message");
log.error("Error message");
```

2. 로그 출력 대상 설정
로깅 프레임워크는 로그 메시지를 다양한 출력 대상으로 보낼 수 있습니다. 예를 들어, 콘솔, 파일, 원격 로그 서버 등 여러 곳으로 로그를 보낼 수 있습니다. 이를 통해 로그를 중앙집중식으로 관리하고, 분석할 수 있습니다.

3. 성능 최적화
System.out을 사용하면 표준 출력 스트림에 직접 쓰기 때문에 성능이 저하될 수 있습니다. 반면, 로깅 프레임워크는 비동기 로깅 및 버퍼링을 통해 성능을 최적화할 수 있습니다.

4. 포맷팅 및 구조화
로깅 프레임워크는 로그 메시지의 포맷을 쉽게 설정할 수 있습니다. 또한, JSON과 같은 구조화된 형식으로 로그를 남길 수도 있어, 로그 분석 도구와의 통합이 용이합니다.

5. 동적 로그 수준 변경
로깅 프레임워크를 사용하면 애플리케이션 실행 중에도 로그 레벨을 동적으로 변경할 수 있습니다. 이를 통해 디버깅이 필요할 때만 상세 로그를 출력하고, 평소에는 간략한 로그만 출력할 수 있습니다.

6. 유지보수성
System.out을 통해 로그를 남기면 코드가 복잡해지고 유지보수가 어려워질 수 있습니다. 로깅 프레임워크를 사용하면 로그 남기는 코드를 체계적으로 관리할 수 있어, 코드의 유지보수성이 높아집니다.

7. 확장성
로깅 프레임워크는 플러그인 형태로 다양한 기능을 추가할 수 있어, 애플리케이션의 요구에 맞게 확장할 수 있습니다.

```java
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Example {

    public static void main(String[] args) {
        log.info("This is an informational message.");
        log.error("This is an error message.");
    }
}
```

**Comment by jane5am** [comment]
이슈 확인하여 수정완료했습니다 감사합니다!
